version: '3.5'
services:
  backend:
    container_name: api
    build: ./src
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - ./env.conf
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:  
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    ports:
      - "5432:5432"  
    volumes:
      - db_volume:/var/lib/postgresql
  
      
  frontend:
    container_name: angular
    build:
      context: .
      dockerfile: proyecto-sw/Dockerfile
    volumes:
      - '.:/proyecto-sw'
      - '/proyecto-sw/node_modules'
    ports:
      - '4201:4200'
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_volume: